---
- name: Debug connection variables
  hosts: localhost 
  vars:
    nutanix_username: "{{ lookup('env', 'NUTANIX_USERNAME', errors='warn') }}"
    nutanix_hostname: "{{ lookup('env', 'NUTANIX_HOSTNAME', errors='warn') }}"
    nutanix_password: "{{ lookup('env', 'NUTANIX_PASSWORD', errors='warn') }}"
  tasks:
  - name : Debug NUTANIX_USERNAME
    debug:
      msg: "the username is {{ nutanix_username }}"
      #verbosity: 3   tested with job template verbosity set to 3
    when: nutanix_username is defined

  - name : Debug NUTANIX_HOSTNAME
    debug:
      msg: "the hostname is {{ nutanix_hostname }}"
      #verbosity: 3   tested with job template verbosity set to 3
    when: nutanix_hostname is defined

  - name : Debug NUTANIX_PASSWORD
    debug:
      msg: "the password is {{ nutanix_password }}"
      #verbosity: 3   tested with job template verbosity set to 3
    when: nutanix_password is defined
